/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author MOD-USER
 */
public class MainWindowBandit extends javax.swing.JFrame {

    /**
     * @return the btnStart
     */
    public javax.swing.JButton getBtnStart() {
        return btnStart;
    }

    /**
     * @return the btnStop
     */
    public javax.swing.JButton getBtnStop() {
        return btnStop;
    }

    /**
     * @return the lblNumber0
     */
    public javax.swing.JLabel getLblNumber0() {
        return lblNumber0;
    }

    /**
     * @return the lblNumber1
     */
    public javax.swing.JLabel getLblNumber1() {
        return lblNumber1;
    }

    /**
     * @return the lblNumber2
     */
    public javax.swing.JLabel getLblNumber2() {
        return lblNumber2;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindowBandit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNumber0 = new javax.swing.JLabel();
        lblNumber1 = new javax.swing.JLabel();
        lblNumber2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(btnStart);

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(btnStop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        lblNumber0.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
        lblNumber0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber0.setText("8");
        jPanel2.add(lblNumber0);

        lblNumber1.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
        lblNumber1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber1.setText("8");
        jPanel2.add(lblNumber1);

        lblNumber2.setFont(new java.awt.Font("Segoe UI", 0, 200)); // NOI18N
        lblNumber2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber2.setText("8");
        jPanel2.add(lblNumber2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowBandit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowBandit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowBandit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowBandit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowBandit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNumber0;
    private javax.swing.JLabel lblNumber1;
    private javax.swing.JLabel lblNumber2;
    // End of variables declaration//GEN-END:variables
}
